name: trade_lab
description: "TradeLab"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^8.2.0
  injectable: ^2.5.1
  provider: ^6.1.1
  animated_notch_bottom_bar: ^1.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  injectable_generator: ^2.6.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/XAUUSD_M1.json
