// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13xO-XjWx93KvCr7JxhBR1OjUO4WtHmg',
    appId: '1:352832278769:web:9eba0e1cd7978371001950',
    messagingSenderId: '352832278769',
    projectId: 'trade-lab-2af58',
    authDomain: 'trade-lab-2af58.firebaseapp.com',
    storageBucket: 'trade-lab-2af58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2nlBwknB04E0JxqpaZdoW6GEhIGwUWo',
    appId: '1:352832278769:android:def0656421d6961e001950',
    messagingSenderId: '352832278769',
    projectId: 'trade-lab-2af58',
    storageBucket: 'trade-lab-2af58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFx9precDVR8dTJnwoeoVD2C0SV86Zxs',
    appId: '1:352832278769:ios:bfb9fd97e899f7e5001950',
    messagingSenderId: '352832278769',
    projectId: 'trade-lab-2af58',
    storageBucket: 'trade-lab-2af58.firebasestorage.app',
    iosClientId: '352832278769-m875d4u14b6leq78vcl7fh60blnofo77.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradingGame',
  );
}
