class AppConfig {}

enum AppConfigKey {
  xauusdM1,
  xauusdM5,
  xauusdM15,
  xauusdM30,
  xauusdH1,
  eurusdM1,
  eurusdM5,
  eurusdM15,
  eurusdM30,
  eurusdH1,
  eurusdH4,
  eurusdD1,
  eurusdW1,
  gbpusdM1,
  gbpusdM5,
  gbpusdM15,
  gbpusdM30,
  gbpusdH1,
  gbpusdH4,
  gbpusdD1,
  gbpusdW1,
  usdcadM1,
  usdcadM5,
  usdcadM15,
  usdcadM30,
  usdcadH1,
  usdcadH4,
  usdcadD1,
  usdcadW1,
  usdjpyM1,
  usdjpyM5,
  usdjpyM15,
  usdjpyM30,
  usdjpyH1,
  usdjpyH4,
  usdjpyD1,
  usdjpyW1,
  usdchfM1,
  usdchfM5,
  usdchfM15,
  usdchfM30,
  usdchfH1,
  usdchfH4,
  usdchfD1,
  usdchfW1;

  String get fileName => switch (this) {
        AppConfigKey.xauusdM1 => 'XAUUSD_M1.json',
        AppConfigKey.xauusdM5 => 'XAUUSD_M5.json',
        AppConfigKey.xauusdM15 => 'XAUUSD_M15.json',
        AppConfigKey.xauusdM30 => 'XAUUSD_M30.json',
        AppConfigKey.xauusdH1 => 'XAUUSD_H1.json',
        AppConfigKey.eurusdM1 => 'EURUSD_M1.json',
        AppConfigKey.eurusdM5 => 'EURUSD_M5.json',
        AppConfigKey.eurusdM15 => 'EURUSD_M15.json',
        AppConfigKey.eurusdM30 => 'EURUSD_M30.json',
        AppConfigKey.eurusdH1 => 'EURUSD_H1.json',
        AppConfigKey.eurusdH4 => 'EURUSD_H4.json',
        AppConfigKey.eurusdD1 => 'EURUSD_D1.json',
        AppConfigKey.eurusdW1 => 'EURUSD_W1.json',
        AppConfigKey.gbpusdM1 => 'GBPUSD_M1.json',
        AppConfigKey.gbpusdM5 => 'GBPUSD_M5.json',
        AppConfigKey.gbpusdM15 => 'GBPUSD_M15.json',
        AppConfigKey.gbpusdM30 => 'GBPUSD_M30.json',
        AppConfigKey.gbpusdH1 => 'GBPUSD_H1.json',
        AppConfigKey.gbpusdH4 => 'GBPUSD_H4.json',
        AppConfigKey.gbpusdD1 => 'GBPUSD_D1.json',
        AppConfigKey.gbpusdW1 => 'GBPUSD_W1.json',
        AppConfigKey.usdcadM1 => 'USDCAD_M1.json',
        AppConfigKey.usdcadM5 => 'USDCAD_M5.json',
        AppConfigKey.usdcadM15 => 'USDCAD_M15.json',
        AppConfigKey.usdcadM30 => 'USDCAD_M30.json',
        AppConfigKey.usdcadH1 => 'USDCAD_H1.json',
        AppConfigKey.usdcadH4 => 'USDCAD_H4.json',
        AppConfigKey.usdcadD1 => 'USDCAD_D1.json',
        AppConfigKey.usdcadW1 => 'USDCAD_W1.json',
        AppConfigKey.usdjpyM1 => 'USDJPY_M1.json',
        AppConfigKey.usdjpyM5 => 'USDJPY_M5.json',
        AppConfigKey.usdjpyM15 => 'USDJPY_M15.json',
        AppConfigKey.usdjpyM30 => 'USDJPY_M30.json',
        AppConfigKey.usdjpyH1 => 'USDJPY_H1.json',
        AppConfigKey.usdjpyH4 => 'USDJPY_H4.json',
        AppConfigKey.usdjpyD1 => 'USDJPY_D1.json',
        AppConfigKey.usdjpyW1 => 'USDJPY_W1.json',
        AppConfigKey.usdchfM1 => 'USDCHF_M1.json',
        AppConfigKey.usdchfM5 => 'USDCHF_M5.json',
        AppConfigKey.usdchfM15 => 'USDCHF_M15.json',
        AppConfigKey.usdchfM30 => 'USDCHF_M30.json',
        AppConfigKey.usdchfH1 => 'USDCHF_H1.json',
        AppConfigKey.usdchfH4 => 'USDCHF_H4.json',
        AppConfigKey.usdchfD1 => 'USDCHF_D1.json',
        AppConfigKey.usdchfW1 => 'USDCHF_W1.json',
      };
}
